export interface Task {
  id?: string; // Optional, as it might be generated by the backend/DB
  title: string;
  description: string;
  status: 'pending' | 'in-progress' | 'completed'; // Or a simpler boolean 'completed'
  createdAt?: string; // Optional, backend will likely set this
}